### ISSUE TITLE
Settings structure for archives

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-core#137]
Build a settings structure for archives. Some interface to allow settings configuration and defaults.

First setting: auto-lock time period, default 10 minutes.

**Comment by perry-mitchell** [comment]
Closed as this has been provided by buttercup-config.

**Comment by exside** [comment]
@perry-mitchell hm, how do I access buttercup-config? Can't see anything in that direction on v1.7.1?

**Comment by perry-mitchell** [comment]
Lib is here @exside: https://github.com/buttercup/config

We'll be using that in the UIs in upcoming versions.
