### ISSUE TITLE
Nextcloud datasource support

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-core#147]
Add support for nextcloud.

**Comment by jancborchardt** [comment]
Cool! :) Just to make sure it's written correctly in the interface, it's "Nextcloud" with only the N capitalized. ;)

You can find the logo in different variations at https://github.com/nextcloud/promo - probably best would be "nextcloud-logo" or "nextcloud-logo-white". Let me know if you need any modification or special size. :)

**Comment by perry-mitchell** [comment]
Thanks @jancborchardt - We'll be getting to this soon. Is there such a thing as a working demo Nextcloud server we could use during integration testing? Or would it just be best to up a machine locally?

**Comment by jancborchardt** [comment]
@perry-mitchell ah sorry, saw this too late but yeah in the pull @sallar correctly linked the https://demo.nextcloud.com :)
