### ISSUE TITLE
Archive Manager’s EventEmitter swallows errors

### ISSUE THREAD

**Issue by sallar** [buttercup/buttercup-core#169]
When using the Archive Manager's events like so:

``` js
archiveManager.on('sourceAdded', function __handleNewSource(sourceInfo) {
  // do something with "sourceInfo"
});
```

if something throws an error inside the callback function `__handleNewSource`, the error will be handled by `buttercup-core` and the application crashed without a meaningful error.

The EventEmitter callback should not break the `buttercup-core`. Or am I doing something wrong...?

**Comment by perry-mitchell** [comment]
Yep this looks dodgy. Will change it to async as per our discussion.
