### ISSUE TITLE
Add new Cloud Services

### ISSUE THREAD

**Issue by regoremor** [buttercup/buttercup-core#187]
Will you add other Cloud Services such as:

 - ~~[ ] OneDrive~~
 - ~~[ ] Amazon Drive~~
 - [x] Google Drive

**Comment by perry-mitchell** [comment]
I think we may add some of those, yes.. I can't comment regarding timelines or priorities, but I don't see any reason why we wouldn't support any of the items you listed. Their adoption will depend largely on our available resources and how difficult they are to implement. And PRs are of course welcome 😊.

Some notes on those items:

 * Box supports WebDAV. We should check its connectivity using our regular adapter. If it functions we could add it as first-party storage.
 * OneDrive seems to have a nice looking [npm package](https://www.npmjs.com/package/onedrive-api).
 * Amazon Drive also seems to have an [npm package](https://www.npmjs.com/package/amazon-drive).
 * Google Drive looks awful imo. I've checked it before and decided against integrating it at the time. I don't think that I'll personally attempt this one any time soon.

**Comment by regoremor** [comment]
Thank you.

**Comment by perry-mitchell** [comment]
We are now tracking these in our [roadmap](https://github.com/buttercup/roadmap/blob/master/roadmap/CLOUD_SERVICES.md). For now we won't support Google Drive, unless someone offers some assistance with regards to an integration.

**Comment by perry-mitchell** [comment]
Tested Webdav with Box, and it works perfectly on desktop.

**Comment by eflames** [comment]
I would love to have the Google Drive integration, I use Dropbox only to save bcup files, no more, I think the space that they offer for free plan is a joke (having 15gb en GDrive my main email platform and 50GB in mega) and the other platforms I dont even know them.

I will stay alert to next buttercup updates for this <3 thank u guys.

**Comment by BinaryShrub** [comment]
+1

I only use Google Drive, once support is added, I'll give it a shot!

**Comment by perry-mitchell** [comment]
There's a small possibility google drive support will be added in core this week.. let's see!

**Comment by perry-mitchell** [comment]
Removed Box as the implementation is out of date, and they're [deprecating WebDAV](https://community.box.com/t5/Box-Product-News/Deprecation-WebDAV-Support/ba-p/55684).

**Comment by eflames** [comment]
> There's a small possibility google drive support will be added in core this week.. let's see!

Yes!!... Small it is much better than nothing. Thanks!

**Comment by perry-mitchell** [comment]
I've created a Google Drive client here: https://github.com/buttercup/googledrive-client

It should be enough to add full Drive support to Buttercup. Next step is adding it as a datasource..

**Comment by perry-mitchell** [comment]
I'll be closing this issue with the Google drive support (too broad).

**Comment by perry-mitchell** [comment]
Released in 2.11.0

**Comment by mmarodin** [comment]
Any news for OneDrive as new supported Cloud Service?
