### ISSUE TITLE
Support more than website passwords

### ISSUE THREAD

**Issue by EgoAleSum** [buttercup/buttercup-core#196]
It would be great if we could use Buttercup to store generic secrets, not just website passwords.

For example:
- Passwords for stuff other than websites (I'm thinking, in my case, my SSH private keys, servers, etc)
- Credit/debit card numbers and PINs
- Notes - ie. anything else plain text

Buttercup seems to have really solid foundations, so it'd be a matter of building on top of that :)

**Comment by perry-mitchell** [comment]
Thanks @EgoAleSum - This is already possible by using [entry facades](https://github.com/buttercup/buttercup-core/blob/master/source/node/system/entryFacadeFields.js). The support is there in the core library, but hasn't yet been used for GUI upgrades in the various GUI applications.
