### ISSUE TITLE
[Feature] Auto-lock after specified time

### ISSUE THREAD

**Issue by exside** [buttercup/buttercup-core#209]
It seems to be a quite common feature in other password managers to be able to specify a time interval after which the database gets locked down automatically and the user has to re-enter the master password. This seems quite important as many will forget to lock their databases (quite sure about it), this could also mitigate #19 to a certain extent.

**Comment by exside** [comment]
Seems something like that was planned as of #137 but can't find it...

**Comment by perry-mitchell** [comment]
Yep! You go it. Once we roll out the config lib into the various apps, auto-lock duration will be configurable (among other settings).
