### ISSUE TITLE
CSV export

### ISSUE THREAD

**Issue by exside** [buttercup/buttercup-core#211]
An export of all database entries in a more "transportable" format would be very useful. An additional feature that would be cool (that most other PW managers also do not seem to have) would be selective export, e.g. I can select either groups or single entries within a group and just export these instead of having always everything in the database exported and then having to go trough an insane amount of CSV data and cherrypick the entries that are actually needed...

**Comment by perry-mitchell** [comment]
Definitely needed!

**Comment by perry-mitchell** [comment]
Renamed for scope.. I think CSV export should be enough to get started. Once we have such a feature future formats will be much easier.

**Comment by perry-mitchell** [comment]
My plan would be a format like so:

```csv
type,id,parent,name,value
group,86617959-f47b-4adc-aa45-c422954d309c,,Banking,
group,2c15a86f-260b-4364-b05c-1b998b7590f4,,Email,
group,e9cd58bb-4123-4c13-b8d1-d35881594332,2c15a86f-260b-4364-b05c-1b998b7590f4,Work mail,
entry,c3c3f254-8c55-4409-b17d-695c38008442,86617959-f47b-4adc-aa45-c422954d309c,,
entry-property,,c3c3f254-8c55-4409-b17d-695c38008442,title,My Bank
entry-property,,c3c3f254-8c55-4409-b17d-695c38008442,username,jane-doe
entry-property,,c3c3f254-8c55-4409-b17d-695c38008442,password,1234
entry-property,,c3c3f254-8c55-4409-b17d-695c38008442,url,https://bank.com
```

Which basically resembles:

![image](https://user-images.githubusercontent.com/3869469/42532011-2c06a9fe-848e-11e8-8d40-643c7dbac8c0.png)

**Groups** and **Entries** are quite easy, but the fact that entries can have various properties makes them tricky to map to a flat structure. Any ideas @exside @sallar ?

**Comment by perry-mitchell** [comment]
**Or**, if we follow similar formats to other managers which only export entries, per se:

```csv
!group_id,!group_name,id,title,username,password,url,secret
86617959-f47b-4adc-aa45-c422954d309c,Banking,c3c3f254-8c55-4409-b17d-695c38008442,My Bank,jane-doe,1234,domain.com,Some text!
2c15a86f-260b-4364-b05c-1b998b7590f4,Mail,45483d52-290d-48bb-8bed-4701691d975d,Hotmail,person@hotmail.com,abc123,hotmail.com,
```

Which resembles:

![image](https://user-images.githubusercontent.com/3869469/42532528-d7eb1a7e-848f-11e8-9768-60298d8a3533.png)

It may be that this is a nicer solution, however some things to note:
 * White space values will/should be ignored
 * Nested groups **are not preserved** in this method. BCUP -> CSV -> BCUP will not produce the same result when nested groups are used..

**Comment by fmommeja** [comment]
Thank you so much @perry-mitchell to work on this highly needed feature !   =D

Related to [your previous comment](https://github.com/buttercup/buttercup-core/issues/211#issuecomment-403934723), maybe could you set the _entry_ _value_ to the number of attached _entry-property_ lines (3 by default, 4 in your example _or, if related to numbering increment starting at 0 in js,_ 2 by default, 3 in your example) ?

**Comment by perry-mitchell** [comment]
@fmommeja I'm actually starting to lean to my second proposal.. It's similar to how other managers do it, and it means 1 line per "entry", which is quite neat. The first proposal requires detailed knowledge of _how_ to read the CSV, whereas the second does not..

**Comment by fmommeja** [comment]
@perry-mitchell Well the important part of it is that you can export every data entered and secured by Buttercup…
I wouldn't blame you for choosing the second proposal as long as all my data can still be exported.  ;)

**Comment by perry-mitchell** [comment]
I've created an export project here: https://github.com/buttercup/buttercup-exporter

**Comment by perry-mitchell** [comment]
This is now done and merged into buttercup desktop. It _should_ go out with 1.10.
