### ISSUE TITLE
[Feature] Customize "Archive" Display Text

### ISSUE THREAD

**Issue by exside** [buttercup/buttercup-core#212]
I'm talking about the round "Icon" in the left sidebar, we can already customize the color of it, why not the text? Of course it can stay the default to take the archive's name, but it doesn't seem too hard to allow users to specify a custom letter (or two)...not very important feature, just wanted it once and couldn't do it =)...

**Comment by perry-mitchell** [comment]
This should be on the buttercup/buttercup-desktop repo, as this is the repo for the core library. I'll close this one..
