### ISSUE TITLE
Failing to unlock my archive

### ISSUE THREAD

**Issue by danielfranca** [buttercup/buttercup-core#218]
Hi guys,
Not sure if here is the right place to open this issue.

I'm not being able to unlock my archive anymore.
I got this error message or other one similar
**"ArchiveManager is not defined"**
It happens after connected to the host, select the file and then type the master password.

The file is on a cloud provider, using WebDAV to connect.

Googling it I found other people's having similar issue while offline, however, I'm online, and I've tried to open it in different clients, browser extension, desktop client, mobile client... always the same error.

I'm afraid the file must be corrupted.
Any idea what might be happening and how to fix it?

**Comment by perry-mitchell** [comment]
Hi,

401 unauthorised is an issue with your file host, not with the vault file itself. What sort of connection are you making? What type of host? Can you login normally through the website?

**Comment by danielfranca** [comment]
I'm sorry, this new error might be because I have tried changing my password on the host.
But I tried changing because it was giving me another error.
The error is: **"ArchiveManager is not defined"**
It happens after connected to the host, select the file and then type the master password.

**Comment by perry-mitchell** [comment]
Very weird issue! What application are you using? Desktop, browser ext., mobile?

**Comment by perry-mitchell** [comment]
@danielfranca We patched an issue on the extension recently: buttercup/buttercup-browser-extension#152

Could this have been it?

**Comment by danielfranca** [comment]
I'm using Firefox extension, desktop and mobile
Now after updating the Firefox extension it is working and the desktop is also working, but the mobile app is still failing with the same error.

**Comment by perry-mitchell** [comment]
Sorry! Mobile app update will be released shortly..

**Comment by danielfranca** [comment]
Everything seems to be working now
Thanks!
