### ISSUE TITLE
[Stability] Replace fetch with cowl

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-core#229]
Replace fetch/axios usage with cowl - our new request toolkit for cross-platform requests.

**Comment by mikesol** [comment]
I'm not sure if this is helpful, but hopefully it gets the issue started on the right foot! https://github.com/buttercup/buttercup-core/pull/259
With this in place, it is possible to progressively migrate the codebase from a `fetch` to `axios` API, or just use `fetch` but with `axios` backing the requests.

**Comment by perry-mitchell** [comment]
I’m sorry I didn’t update this sooner, but axios might not be ideal here. It’s not maintained really and we’d only seen something more lightweight.

We built cowl (https://github.com/perry-mitchell/cowl) for this and have begun using it elsewhere in the platform. I’m sorry if this has wasted time on your part - would you consider changing again from axios to cowl?

**Comment by mikesol** [comment]
Cool, not a waste of time at all, happy to check it out. Could you rename the issue?

**Comment by mikesol** [comment]
And would you want to start with a `fetch -> cowl` bridge so cowl was being used internally? This would allow a slow migration away from `fetch`. If you'd prefer it to be in one fell swoop, that'd be a bigger PR, but it's definitely doable, I just may not have time to do it all.

**Comment by perry-mitchell** [comment]
Bridge is fine if it means more results - I’m happy to keep it that way. We just appreciate the help 🙏

I’ll rename the issue. Cowl is still fresh so we can take the transition at a slower pace. It’ll help us retain a more cross-platform codebase as axios, fetch and others all have cross platform woes. Buttercup core must be isomorphic.
