### ISSUE TITLE
[FEAT REQ] Use SSH key as master password

### ISSUE THREAD

**Issue by Elrondo46** [buttercup/buttercup-core#238]
Can you implement it ?

**Comment by perry-mitchell** [comment]
Hi @Elrondo46 - The underlying library `iocane` supports file-based authentication, but we've chosen to avoid implementing this in the Buttercup suite for now. It's only doable on the Desktop application - it wouldn't work on the extension or mobile app.

For that reason we unfortunately won't be adding this feature. If however you're using buttercup core in another application and don't need our UIs, you can simply read the contents of the ssh key, maybe hash it, and use that as the password.
