### ISSUE TITLE
Adding files to an archive

### ISSUE THREAD

**Issue by claystation** [buttercup/buttercup-core#246]
Hello!

I recently discovered Buttercup and I already like it very much. The support for all platforms is amazing! Works really well! I was looking for a keepass client for Iphone/Mac but then i stumbled upon this. Amazing product!

I only miss a feature in comparison to Keepass. There is no way to securely add files to an entry. Like, if i want to transfer my Private SSH Key to another computer, I would like to do save it in a bcup archive and transfer it. Is it possible to add this to a future release? 
It is not a deal breaker for me right now, i will definitely start using bcup!

Also, please correct me if i am in the wrong repo or if i did not provide enough information.

Thank you so much! Like to hear from you soon!

**Comment by perry-mitchell** [comment]
Hi @claystation - actually this has just been started.. You can check out the progress here, on the [bcupfs](https://github.com/buttercup/bcupfs) project. Once it's complete we'll use it to attach encrypted files to archives.

> I recently discovered Buttercup and I already like it very much. The support for all platforms is amazing! Works really well! I was looking for a keepass client for Iphone/Mac but then i stumbled upon this. Amazing product!

Thanks a lot for the kind words! I'm really glad you like it. We're trying to make it the best there is 😊

**Comment by claystation** [comment]
Yess! Thank you for your reply. I will be sure to watch the fs repo. Keep it up!
