### ISSUE TITLE
[Feature] Credit card and TOTP

### ISSUE THREAD

**Issue by loxK** [buttercup/buttercup-core#250]
I am an avid user of Enpass, but it is closed source.

I miss 4 things to switch:
- TOTP field + autocomplete 
- Credit card fields + autocomplete
- Secondary secret/password fields as in #210 
- Multi-line text field

**Comment by perry-mitchell** [comment]
Thanks @loxK:

 * TOTP - I've added as an issue: https://github.com/buttercup/buttercup-core/issues/251
 * Credit cards are already supported, pending UI upgrades
 * As you mentioned, #210 details secret custom fields 
 * Multi-line text fields are also supported already, pending the same UI upgrades as point 2.

I'll close this issue as I feel the sub-issues are being handled.
