### ISSUE TITLE
TOTP support

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-core#251]
Support for TOTP and HOTP.

**Comment by jmfederico** [comment]
Generation in JS:
https://github.com/jaden/totp-generator

**Comment by perry-mitchell** [comment]
Leaving this example twitter TOTP auth string here for later reference:

`otpauth://totp/Twitter:undefined?secret=DAO3AGTWDCXQ25T4&issuer=Twitter`

**Comment by perry-mitchell** [comment]
After having a bit of a think on this, I think this can be closed as of 2.13.0. The responsibility of the core here is to store the OTPAUTH URIs, but not necessary to generate anything in the way of output.. that should be done in each UI part.
