### ISSUE TITLE
Vault corrupt? Salt must be provided

### ISSUE THREAD

**Issue by claystation** [buttercup/buttercup-core#252]
Hi, i need some urgent help. I cannot seem to open my vault anymore. 

Whenever i try to open it on mobile (iOS) or desktop (Mac OS) i get the following error:

Failed unlocking source: xxxx-xxxx-xxxx-xxxx: Failed mapping credentials to a source: Failed deriving key: Salt must be provided.

Dev tools console is empty. 200 OK response on the vault file (also downloaded it and tried opening locally, same result)

Creating new vaults and opening them is fine on desktop.
Any more info i can provide?

I hope this is fixable?

**Comment by perry-mitchell** [comment]
@claystation At the end of your vault file you'll see some `$` sign delimited arguments, like so:

`...O3DmrAgh0A==$f3d0a22c8856e2e9a5e0890670c6fccd$GTWYGu5KnEbY$6600efb9ba4aa68a5cc5220fece62f1566462e599f1beed970b6b877731c6811$250000$cbc`

The salt is the **fourth** last item. In the text above, the salt would be `f3d0a22c8856e2e9a5e0890670c6fccd`.

Can you confirm that this value resembles the text I've shared here? It should be hexadecimal and of the same length (32).

**Comment by claystation** [comment]
To be fair, after a while i reverted back to an older version of my vault so at least i could access all my passwords again. More worth to take time to reset some passwords instead of waiting for a reply. So, i don't actually know if the salt is there. Neither do i know how i could see "the end of my vault file", like in a text editor or something?

**Comment by perry-mitchell** [comment]
Yes, just in a text editor would work. Completely understand not being able to wait for an answer.

If you notice further issues please let us know, I'll close this in the meantime as there's nothing to do here right now.
