### ISSUE TITLE
[feature] Password History

### ISSUE THREAD

**Issue by neojp** [buttercup/buttercup-core#253]
1Password has a feature that allows you to keep your previous password whenever it's updated.
Based on the 1PIF file it looks like an array of objects with a date and password value.

```json
{
    "passwordHistory": [{ "value": "pa$$word", "time": 1483804849 }]
}
```

Looks like a nice feature to have on core, but it could easily be implemented on the clients as well.

**Comment by perry-mitchell** [comment]
We have this already, as we use deltas to update vaults so we could easily store previous values. Just need to expose it on the UI :)

**Comment by perry-mitchell** [comment]
I closed this thinking there was an issue already, but there wasn’t it seems. I’ll reopen this for tracking the functionality I mentioned. Thanks!

**Comment by perry-mitchell** [comment]
Implementation should handle the setting of historical property values while deltas are being parsed and applied. It should be noted that the facades platform should be updated to also handle historical values so they can be used in the UI shared library.

**Comment by perry-mitchell** [comment]
This is handled and available in the browser ext already.
