### ISSUE TITLE
Vault Size Grows Very Large

### ISSUE THREAD

**Issue by moussaclarke** [buttercup/buttercup-core#287]
Great app by the way, have been using it for the last couple of years and it’s a very welcome OS alternative to LastPass etc.

I’ve noticed that vault files seem to suddenly grow very large in size, which affects performance, making loading via chrome extension and desktop very slow, and rendering the mobile app pretty much unusable. Wondered if this is a known issue/feature/bug but couldn’t find anything on GH. Also not sure whether this issue is more appropriate in core, desktop, or here in the chrome extension repo - but posting here because that's what I use the most day to day.

I’ve been solving it by exporting everything to csv via the desktop app and re-importing to a freshly created vault. The last vault grew to 31mb within a couple of weeks, previous one to 100mb which slowed loading times right down to a crawl. I have around 200 entries in there. Freshly created/imported vault is around 1MB, which is closer to what I would expect and loads super fast.

I can't give precise steps to re-create this, it seems to occur eventually after repeated general use - i.e. opening/closing/saving entries. The increase in size seems to be pretty sudden. The last time it happened I noticed a marked slowdown in performance/loading, rather than a gradual worsening, which then prompted me to check the file size again. I guess this suggests some specific event causing the size increase, however I can't be totally sure that's an accurate perception.

I’m on Mac OS Catalina/Mojave across various desktops/laptops, using the desktop app and chrome extension but mostly the latter on a daily basis, and very occasionally the phone app on Android 9. Vault stored in cloud.

**Comment by perry-mitchell** [comment]
Still looking for help on this - we really need a **test vault** that contains the excess data so we can analyse it. I've not been able to reproduce this myself yet. Please let us know if you can help by testing in a sample vault that you might send to us if it starts growing in size.

In the meantime I think it's been solidly confirmed that this is reproducible in all of our applications. This is our highest priority right now.

**Comment by matiboux** [comment]
Here is a GIF showing the size evolution of the archive with only small edits.

![GIF](https://user-images.githubusercontent.com/7428799/90642639-f0896600-e232-11ea-9101-3636ee1d2a0d.gif)

Attached, you'll fin the three files seen in the GIF.

[TestArchives.zip](https://github.com/buttercup/buttercup-core/files/5096818/TestArchives.zip)

The password is `test` ♪

**Comment by perry-mitchell** [comment]
Thanks @matiboux - I've been doing the same locally now for some minutes, and can see the same size increase. This is minor, however, compared to the 100+mb reported - I'd like to see one of those vaults. Specifically the issue surrounding your last statement in the other issue:

> The archive over 100 MB could not be opened so I tried to open the 34.2 MB one: worked after some loading.
> I've then tried to export the archive and import it back into a blank archive to see the "true" size of its content: 447.66 KB.

I want to know what's inflating the size so much.

The reason the vault size grows those couple of kb each time you make a change is because it's storing deltas. It doesn't store your vault data, it stores **every change made**. This is why the size still increases even if you delete items. It has a cap however, at X lines of history, but this seems to not have an effect.

**Comment by perry-mitchell** [comment]
And just as I said it, I found what's causing the bloat! We use a padding command to identify important changes in our deltas, and it seems like a bug has caused it to go nuts, inflating the file with essentially nothing:

```javascript
[
  // ...
  "pad 3f869dad-3716-4787-9690-96c677035d56",
  "pad 450da671-8a7d-4b23-b365-53dfb002e9bb",
  "pad 31333d21-3f19-40cc-a141-d6e69250fe17",
  "pad 2caf6d37-e9fe-473e-99a7-9a9d46f2963a",
  "pad 28f24a17-a5f8-44a8-ac36-8c0c7708ae4c",
  "pad 6b0ccc65-d35e-42f8-8cf6-47024a3a20f5",
  "pad 76698b4a-aa3d-48d4-9c89-ee807918273c",
  "pad 743e9225-3cd9-4065-8734-82433f17d893",
  "sep 5e242fe2-4e36-4b66-9e86-ab9a93d251fc utf8+base64:ZmdmZ2Zn utf8+base64:NTQ1",
  "pad 837fbff0-cf7f-41ff-b1eb-50776b6602f0",
  "pad 0341e7b0-14c9-40d8-a2d2-78522840e547",
  "pad 75ef2f55-4cd4-4ed6-8591-dd38e5f0633a",
  "pad 51107c56-a207-49d9-b008-9fd76447dd78",
  "pad e9b79550-b819-419a-af5c-a857f265cd62",
  "pad 23accf98-c8a7-45b1-b6bf-0c4c46d371cc",
  "pad b18a1482-a8d4-43a5-aecf-9f841304f423",
  "pad 5fca9320-ac3b-4063-81e3-59de6e58eb24",
  "sep 5e242fe2-4e36-4b66-9e86-ab9a93d251fc utf8+base64:dHQ= utf8+base64:NDU0NQ==",
  "pad ba33958f-d2b2-4f21-b1b5-23b0981edadb",
  "pad f231c816-8eb2-4388-a058-190b293cc920",
  "pad a853c6db-0963-46af-b616-6f13e82e41c8",
  "pad 119f7c60-8808-40c6-8604-a92ed670ae35",
  "pad b47fe5e1-b4ab-45b1-9c30-df8c86687f05",
  "pad 600f1190-b3c1-411b-b750-51a452b0bab1",
  "pad 11995c30-737f-4ea4-b13c-7967b4f030fd",
  "pad 219fa83e-9a33-48c4-bbd4-09de661f6340",
  "cen b5a178cb-946c-4978-8130-bf91f382a315 79f9a5d3-9160-432d-b7ba-dadcddc373cd",
  "pad 45452592-0844-4328-81ca-7d2dccc82a5d",
  "pad a0c50443-f2fe-421c-94f7-e1054986ff2f",
  "pad 933a7e17-0991-4965-81ff-37babf37871c",
  "pad 706ba947-fd8f-4492-98b1-bf2131ac56e6",
  "pad dddd2b77-1ac9-4261-a292-56d9d66f5d0c",
  "pad ae9b0f5d-414f-4980-a093-4bb6890397b7",
  "pad 488f5e61-9f8b-4ff8-a8f0-6363144a54c1",
  "pad 77052f6d-d739-4fcc-8681-45829fcb2373",
  "sea 79f9a5d3-9160-432d-b7ba-dadcddc373cd utf8+base64:QkNfRU5UUllfRkFDQURFX1RZUEU= utf8+base64:bG9naW4="
  // ...
]
```

I'll look into what's causing this immediately.

**Comment by perry-mitchell** [comment]
Hmm.. I can't reproduce the issue when debugging locally against the source. All the padding is normal. I also can't yet see any condition where multiple padding commands would be added.

If nothing else I will add a strip function to remove duplicate paddings from the file before saving.

**Comment by matiboux** [comment]
> This is minor, however, compared to the 100+mb reported - I'd like to see one of those vaults.

Yes, it seems to be somehow exponential.
My large archive went from 22 MB to 35 MB to 110 MB according to my Dropbox's file history.

**Comment by perry-mitchell** [comment]
@matiboux Great find! And yes, I can confirm the same. I've found the issue now actually and it's how we interpret the _last_ command run in our delta processor. It's detecting if the last command was a **pad** and then skipping adding another, but it wasn't checking the _next_ command incoming. So there was basically a logic error with this, and as it'd parse **every** line in a vault's history upon unlock and save, the vaults seem to add a new pad to every single place there's a pad command already, growing the size almost exponentially as you mentioned.

I'm going to try and patch this now, but it might take some days or so to land this on every app.

**Comment by matiboux** [comment]
Cool ! Good job and thanks ! 👌
I think I can wait a few days ^^

**Comment by perry-mitchell** [comment]
@matiboux Thanks to you for pushing this over the line! What a headache this must have been for you and everyone else.. Can't believe I haven't experienced it myself (to this degree). Thankfully I don't need to add a cleanup phase for vaults, as saving an existing "bloated" vault will cause the excess padding to be stripped away.

**Comment by perry-mitchell** [comment]
Publishing under 4.13.1

**Comment by perry-mitchell** [comment]
Just testing this now in the browser extension, and the change in vault size is drastic:

![image](https://user-images.githubusercontent.com/3869469/90670881-8be30100-e25c-11ea-8be6-4c7f534531c7.png)

**Comment by matiboux** [comment]
Wow, nice!

**Comment by perry-mitchell** [comment]
The following releases should be installed immediately to prevent vault growth and to restore a more optimal vault size:

 * [Desktop 1.20.5](https://github.com/buttercup/buttercup-desktop/releases/tag/v1.20.5)
 * [Browser 2.20.2](https://github.com/buttercup/buttercup-browser-extension/blob/master/CHANGELOG.md#v2202)
 * Mobile ? (to be released)

Please note that you **must save** your vault for the shrinking to take effect.

**Comment by spr2** [comment]
Thank you for solving this! I can confirm my vault has shrunk to reasonable size after saving!
