### ISSUE TITLE
Google Drive Connection does not work (keeps loading)

### ISSUE THREAD

**Issue by shhkid** [buttercup/buttercup-core#292]
Hi everyone,
I'm unable to connect to Google Drive. The connections keeps loading but no result is appearing. 
Neither in the browser addon (CHROME) nor in the desktop application.
I'm running on Linux Mint 20 (ulyana).
Can anyone confirm that there's a bug or is there a problem on my side? 

Version
2.23.0
Browser
name: Chrome
version: 86
fullVersion: 86.0.4240.198
os: Linux

**Comment by perry-mitchell** [comment]
@shhkid Sorry for the lack of response. There's no current issue with the Google Drive connection, at least in the current browser extension version. So I'll close this.

If you detect another issue, please open it on the relevant project repo (browser, for example), as it might get more eyes there.

**Comment by shhkid** [comment]
Hi,
I rechecked it right now and the issue still persists.
