### ISSUE TITLE
OneDrive webdav access

### ISSUE THREAD

**Issue by mmarodin** [buttercup/buttercup-core#306]
Is it possible to use webdav access to OneDrive from my mobile Buttercup app?
I tried but it doesn't work.

401 error :(

Here an example:
https://winscp.net/eng/docs/guide_microsoft_onedrive

Please let me know, thanks

**Comment by perry-mitchell** [comment]
I'd propose not using WebDAV here, as getting the ID/token seems tricky. Let's do a full OAuth integration in #302.
