### ISSUE TITLE
How to Decrypt Vault _Without_ Buttercup?

### ISSUE THREAD

**Issue by zicklag** [buttercup/buttercup-core#308]
To make me more comfortable with the fact that I will be able to decrypt the buttercup vaultm even if, for whatever reason, I didn't have access to buttercup itself, I would like to know the exact format used currently for the buttercup vault, and what steps I'd take to decrypt it manually, probably in another programming language ( i.e. Rust ) or just with CLI tools if such tools exist that will do the decryption necessary.

For instance, it appears the file is basically a header of some sort followed by encrypted, base64 encoded JSON, but what is the exact format, and maybe what is the pseudo code for decrypting the data using only the master password?

I can go comb the source code if necessary, but I appreciate any guidance to make that a little bit easier if it's not too much trouble. Thanks!

**Comment by fkasler** [comment]
@zicklag you should check out this buttercup dump utility: https://github.com/fkasler/butterbrute/blob/main/dump_vault.mjs

It's part of a project that might help if you also forgot your password ;)
