### ISSUE TITLE
Buttercup self-hosted server

### ISSUE THREAD

**Issue by alexaf2000** [buttercup/buttercup-core#311]
I've read about a new feature called self-hosted server for buttercup, I don't know if is under development but that would be a very good solution.

Other kind of web self-hosted passwords managers are pretty limited, ugly and they aren't well integrated.

Make a movement of buttercup to a better password management with even users and groups would be a good movement.

**Comment by perry-mitchell** [comment]
Hi! Thanks for the interest. It is actually, currently, **under development**. I'm trying to set aside more time for it, which is why there's been far less going on in the current repos. I hope to have the first version ready very soon. I'll make it very apparent across all of Buttercup's media.
