### ISSUE TITLE
Lost recovery phrase

### ISSUE THREAD

**Issue by VsPalmer** [buttercup/buttercup-core#314]
Hiya have lost recovery phrase but still able to get on app as have Face ID but am not connected on Coinbase wallet to look a phrase anyway I can somehow recover it, thankyou

**Comment by Yuxanju** [comment]
That’s why it’s important you synchronize your wallet and then you debug it .. it’s very important you do…

**Comment by perry-mitchell** [comment]
Hi. Unfortunately there's no recovery system right now. Just the password that you used to encrypt the vault. That cannot be retrieved or bypassed. Sorry.
