### ISSUE TITLE
Unable to save new entries in vault - Error 423 

### ISSUE THREAD

**Issue by CSparn** [buttercup/buttercup-core#327]
Hi all,

since a few days I get weired errors when I try to add new entries to my vault.
The vault file is placed on an OwnCloud server and synchronized with multiple devices (desktop, mobile and browser).
On all devices and in all apps I get the error 423 - locked. In desktop app I also get an unhandled promise rejection.

Is there any idea to fix this error?

Greetings
C.Sparn

**Comment by toxis** [comment]
Same here with Nextcloud and webdav protocol, have you found a solution?
Seems to happen randomly.

**Comment by perry-mitchell** [comment]
Nothing has changed here regarding webdav in a long time. I'd suspect either something with the service provider (Nextcloud) or some other browser weirdness. 

Regardless, there's nothing actionable here I'm afraid. For an issue to be solved I'd need a way to reproduce it easily. Nextcloud works for me (I use it daily) and I don't use ownCloud personally.

Will reopen if there are more details that might help locate the issue.

> On all devices and in all apps I get the error 423 - locked.

This is most likely an issue with the host, and nothing to do with the client side of things.
