### ISSUE TITLE
bug report: unable to empty trash

### ISSUE THREAD

**Issue by georglauterbach** [buttercup/buttercup-core#329]
### Information about my System

- Desktop @ v2.18.2
- Core @ v6.17.2
- Flags: installed

Running on an M2 MacBook Air with macOS 13.2.1 (22D68) (code name: Ventura).

The `*.bcup` file is located in a private cloud that is shared between multiple devices (and also accessed via WebDAV).

### What's the Problem?

I cannot empty the trash. Pressing the red cross will shortly remove all entries, then they re-appear after a second and then the vault is synchronized.

I am uncertain as to how I provide more debugging information here - please let me know which logs you need and how I can get them.

**Comment by perry-mitchell** [comment]
Can you kindly make a back up of your vault, and then convert it to Format B in the vault options? Does the issue still occur then?

**Comment by georglauterbach** [comment]
I tried that, but it did not resolve the issue.

I cannot delete individual entries in the trash too. Very weird.

**Comment by georglauterbach** [comment]
Any ideas?

**Comment by georglauterbach** [comment]
ping

**Comment by Pemichka** [comment]
Moin,

bei mir tritt exakt das gleiche Problem auf. (Windows 11 und Tresor mit Format B)
Nach Drücken des roten Kreuz leert sich der Papierkorb scheinbar aber mit dem speichern erscheint der Inhalt sofort wieder.

**Comment by perry-mitchell** [comment]
Looking into this now.

**Comment by georglauterbach** [comment]
Thank you so much! I'll wait for this version of core to become available and test it 👍🏼

**Comment by Pemichka** [comment]
Vielen Dank, es funktioniert wieder. Der Papierkorb ist leer.
