### ISSUE TITLE
Implement tests around all commands

### ISSUE THREAD

**Issue by Jameskmonger** [buttercup/buttercup-core#56]
Implement unit tests around all commands using a similar structure to the currently tested ones.

**Comment by Jameskmonger** [comment]
@perry-mitchell Could you assign this to me?

**Comment by perry-mitchell** [comment]
Ensure that when testing **mgr**, that target group IDs beginning with a "0" are tested (addresses #59, covers #39).

**Comment by Jameskmonger** [comment]
Tests around **cmm** have been added in #68 @perry-mitchell

**Comment by Jameskmonger** [comment]
I'm going to pick this back up @perry-mitchell if that's okay?

**Comment by perry-mitchell** [comment]
Sure! Would love to get that coverage up 👍
