### ISSUE TITLE
Remove cmm command

### ISSUE THREAD

**Issue by Jameskmonger** [buttercup/buttercup-core#58]
I can't see any use of the `cmm` command at the moment, would it not make sense to remove it?

**Comment by perry-mitchell** [comment]
2 reasons why I don't think we can:
 * I had planned that the cmm command would be useful for more advanced use-cases involving merge conflicts, but that hasn't been spec'd so much just yet.
 * There are users with existing archives, and removing the command would create issues with these archives.

**Comment by Jameskmonger** [comment]
Sounds good to me @perry-mitchell, but should we particularly worry about users with existing archives?

As we're still in alpha development, maybe a better solution would be to remove the `cmm` command, but introduce a feature that removes the command from any users saved archives when saving. This way the usage will be phased out over time.

**Comment by perry-mitchell** [comment]
I would like to keep backwards compat with all existing archives to the best of our abilities. In other words, if we're to break the compatibility, I want it to be for a very good reason.

I like your idea of stripping it from archives for some time, and removing the command. As long as no errors are thrown for the cmm command, it sounds doable.
